{
 "title": "Legacy Application",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Application Health",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(application_health_score) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Legacy Application Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"legacy_app_count\"})"
    }
   ]
  },
  {
   "title": "Order Request Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"order_count\"})"
    }
   ]
  },
  {
   "title": "Sucessfull Orders",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"order_success_count\"})"
    }
   ]
  },
  {
   "title": "UnSucesfull Orders",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(application_operation_total{operation=\"order_error_count\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Request Per Second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(application_operation_total{operation=\"order_count\"}[$__range])"
    }
   ]
  },
  {
   "title": "Process Performance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(application_operation_duration_seconds)by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Shipping Service Performance",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(application_operation_duration_seconds{component=\"shipping_service\"})by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}